# $FreeBSD: src/gnu/usr.bin/cc/Makefile.tgt,v 1.11.8.1 2009/04/15 03:14:26 kensmith Exp $
# $OpenBSD: Makefile.tgt,v 1.11 2013/05/08 15:30:38 miod Exp $

TARGET_ARCH?=	${MACHINE_ARCH}

.if ${TARGET_ARCH} == "arm"
GCC_CPU=	arm
.elif ${TARGET_ARCH} == "i386" || ${TARGET_ARCH} == "amd64"
GCC_CPU=	i386
.endif
